Search.appendIndex(
    [
                {
            "fqsen": "\\validateDate\u0028\u0029",
            "name": "validateDate",
            "summary": "",
            "url": "namespaces/default.html#function_validateDate"
        },                {
            "fqsen": "\\image_resize\u0028\u0029",
            "name": "image_resize",
            "summary": "",
            "url": "namespaces/default.html#function_image_resize"
        },                {
            "fqsen": "\\resizeImage\u0028\u0029",
            "name": "resizeImage",
            "summary": "",
            "url": "namespaces/default.html#function_resizeImage"
        },                {
            "fqsen": "\\deleteImage\u0028\u0029",
            "name": "deleteImage",
            "summary": "",
            "url": "namespaces/default.html#function_deleteImage"
        },                {
            "fqsen": "\\getMysqlPDO\u0028\u0029",
            "name": "getMysqlPDO",
            "summary": "",
            "url": "namespaces/default.html#function_getMysqlPDO"
        },                {
            "fqsen": "\\existProduct\u0028\u0029",
            "name": "existProduct",
            "summary": "",
            "url": "namespaces/default.html#function_existProduct"
        },                {
            "fqsen": "\\addProduct\u0028\u0029",
            "name": "addProduct",
            "summary": "",
            "url": "namespaces/default.html#function_addProduct"
        },                {
            "fqsen": "\\updateProduct\u0028\u0029",
            "name": "updateProduct",
            "summary": "",
            "url": "namespaces/default.html#function_updateProduct"
        },                {
            "fqsen": "\\getProduct\u0028\u0029",
            "name": "getProduct",
            "summary": "",
            "url": "namespaces/default.html#function_getProduct"
        },                {
            "fqsen": "\\checkLogin\u0028\u0029",
            "name": "checkLogin",
            "summary": "",
            "url": "namespaces/default.html#function_checkLogin"
        },                {
            "fqsen": "\\setLoggedin\u0028\u0029",
            "name": "setLoggedin",
            "summary": "",
            "url": "namespaces/default.html#function_setLoggedin"
        },                {
            "fqsen": "\\setInitials\u0028\u0029",
            "name": "setInitials",
            "summary": "",
            "url": "namespaces/default.html#function_setInitials"
        },                {
            "fqsen": "\\setUserID\u0028\u0029",
            "name": "setUserID",
            "summary": "",
            "url": "namespaces/default.html#function_setUserID"
        },                {
            "fqsen": "\\getUserIDSession\u0028\u0029",
            "name": "getUserIDSession",
            "summary": "",
            "url": "namespaces/default.html#function_getUserIDSession"
        },                {
            "fqsen": "\\getLoginAttempts\u0028\u0029",
            "name": "getLoginAttempts",
            "summary": "",
            "url": "namespaces/default.html#function_getLoginAttempts"
        },                {
            "fqsen": "\\setLoginAttempt\u0028\u0029",
            "name": "setLoginAttempt",
            "summary": "",
            "url": "namespaces/default.html#function_setLoginAttempt"
        },                {
            "fqsen": "\\setUserLoggedinData\u0028\u0029",
            "name": "setUserLoggedinData",
            "summary": "",
            "url": "namespaces/default.html#function_setUserLoggedinData"
        },                {
            "fqsen": "\\setLastArticleWrite\u0028\u0029",
            "name": "setLastArticleWrite",
            "summary": "",
            "url": "namespaces/default.html#function_setLastArticleWrite"
        },                {
            "fqsen": "\\getLastArticleWrite\u0028\u0029",
            "name": "getLastArticleWrite",
            "summary": "",
            "url": "namespaces/default.html#function_getLastArticleWrite"
        },                {
            "fqsen": "\\setSelectedImage\u0028\u0029",
            "name": "setSelectedImage",
            "summary": "",
            "url": "namespaces/default.html#function_setSelectedImage"
        },                {
            "fqsen": "\\getSelectedImage\u0028\u0029",
            "name": "getSelectedImage",
            "summary": "",
            "url": "namespaces/default.html#function_getSelectedImage"
        },                {
            "fqsen": "\\redirectClient\u0028\u0029",
            "name": "redirectClient",
            "summary": "",
            "url": "namespaces/default.html#function_redirectClient"
        },                {
            "fqsen": "\\getPathOverBase\u0028\u0029",
            "name": "getPathOverBase",
            "summary": "",
            "url": "namespaces/default.html#function_getPathOverBase"
        },                {
            "fqsen": "\\returnAlert\u0028\u0029",
            "name": "returnAlert",
            "summary": "",
            "url": "namespaces/default.html#function_returnAlert"
        },                {
            "fqsen": "\\checkCaptcha\u0028\u0029",
            "name": "checkCaptcha",
            "summary": "",
            "url": "namespaces/default.html#function_checkCaptcha"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
